# 既読JSONの保存先
state_dir: ./state

# SlackのWebhook URL
slack_webhook_url: ''

# 既読ハッシュ保持数
max_seen: 50

# HTTPタイムアウト秒
timeout: 20

# 直近N日以内だけ通知
cutoff_days: 1

# 実行1回あたりの通知最大件数
max_emit: 20

feeds:
  - name: OpenAI Blog
    url: https://openai.com/blog/rss.xml
  - name: Google AI Blog
    url: https://blog.google/technology/ai/rss/
  - name: The latest research from Google
    url: https://research.google/blog/rss/
  - name: DeepMind Blog
    url: https://deepmind.google/blog/rss.xml
  - name: The Decoder
    url: https://the-decoder.com/feed/
  - name: VentureBeat AI
    url: https://venturebeat.com/category/ai/feed/
  - name: TechCrunch AI
    url: https://techcrunch.com/category/artificial-intelligence/feed/
  - name: MIT Technology Review (AI)
    url: https://www.technologyreview.com/topic/artificial-intelligence/feed/
  - name: Berkeley AI Research (BAIR) Blog
    url: https://bair.berkeley.edu/blog/feed
  - name: Hugging Face Blog
    url: https://huggingface.co/blog/feed.xml
  - name: AWS Machine Learning Blog
    url: https://aws.amazon.com/blogs/machine-learning/feed/
  - name: NVIDIA Technical Blog (Generative AI)
    url: https://developer.nvidia.com/blog/category/generative-ai/feed/
  - name: NVIDIA Technical Blog (Conversational AI)
    url: https://developer.nvidia.com/blog/category/conversational-ai/feed
  - name: MarkTechPost
    url: https://www.marktechpost.com/feed/
  - name: arXiv cs.AI (new)
    url: https://export.arxiv.org/rss/cs.AI
  - name: arXiv cs.CL (NLP)
    url: https://export.arxiv.org/rss/cs.CL
  - name: Papers with Code — Trending
    url: https://huggingface.co/blog/feed.xml
